version: '3.9'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && rails server -b 0.0.0.0 -p 3001"
    volumes:
      - ./backend:/app
    ports:
      - '3001:3001'
    environment:
      - RAILS_ENV=development
      - REDIS_URL=redis://redis:6379/1
      - WEATHER_GEOCODING_URL=https://geocoding-api.open-meteo.com/v1/search
      - WEATHER_QUERY_URL=https://api.open-meteo.com/v1/forecast
    depends_on:
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001
    volumes:
      - ./frontend:/app
    command: npm run dev
    depends_on:
      - backend

  redis:
    image: redis:7.0
    ports:
      - '6379:6379'
